#h2 test db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1


# JPA & Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

#App domain and photo folder
api.domain=http://localhost:8080
photo.public.path=target/test-uploads/photos
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.enabled=true

#Test JWT
app.jwt.secret=nj7kab3zhoijenDI3U54a6uPPndz2i3D3ESa9m7s6ppze80XGsd3AP

#Allowed cors origin for dev
cors.allowed-origin=http://localhost:4200

#Cookie security (false for test environment)
app.cookie.secure=false

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false